version: "2"
sql:
  - engine: "postgresql"
    queries: "./db-queries.sql"
    schema: "./db-schema.sql"
    gen:
      go:
        package: "sql"
        sql_package: "pgx/v5"
        out: "../../../internal/dbmodel/db_query"
        emit_json_tags: true
        emit_db_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: false        

